DECLARE 
       @NOTA1 DECIMAL(7,4),
	   @NOTA2 DECIMAL(7,4),
	   @NOTA3 DECIMAL(7,4),
	   @NOTA4 DECIMAL(7,4),
	   @MEDIA DECIMAL(7,4);

SET @NOTA1 = 6;
SET @NOTA2 = 6.5;
SET @NOTA3 = 7;
SET @NOTA4 = 3.6;


SET @MEDIA = (@NOTA1 + @NOTA2 + @NOTA3 + @NOTA4) / 4;

PRINT 'MEDIA: '; 
PRINT @MEDIA;